# Generated by Django 4.1.6 on 2023-07-12 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroupGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RandomOrgRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requestUrl", models.URLField(blank=True, null=True)),
                ("requestBody", models.TextField(blank=True, null=True)),
                ("statusCode", models.IntegerField(blank=True, null=True)),
                ("headers", models.TextField(blank=True, null=True)),
                ("responseBody", models.TextField(blank=True, null=True)),
                ("requestDate", models.DateField(auto_now_add=True)),
                ("functionName", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grupa",
                        to="manager.groupgame",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_one_score", models.IntegerField(default=0)),
                ("team_two_score", models.IntegerField(default=0)),
                (
                    "team_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_one",
                        to="manager.team",
                        verbose_name="Drużyna Pierwsza",
                    ),
                ),
                (
                    "team_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="team_two",
                        to="manager.team",
                        verbose_name="Drużyna Druga",
                    ),
                ),
            ],
        ),
    ]
