# Generated by Django 4.1.6 on 2023-07-19 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="finished",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="MatchesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_in_order", models.IntegerField(unique=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="manager.match"
                    ),
                ),
            ],
        ),
    ]
